### ISSUE TITLE
Oracle

### ISSUE THREAD

**Issue by jaidetura55** [galiy/kaspa-pool#2]
Status on cli  "oracle connect: " what it purpose
I do compile using nodejs and change to many nodejs version but all error.Please help me rid this error.

**Comment by galiy** [comment]
This is not a complete software package, you will not be able to use it. It lacks a database and programs written in Oracle. I will not post it here. Use it as you can or do not use it at all.

**Comment by jaidetura55** [comment]
Thank you sir for the solution for oracle issue.
I succed to run it but last error i get regard to ember error on web page missing translation

**Comment by galiy** [comment]
You won't be able to run it. Stratum sends statistics to Oracle. Frontend takes data from Oracle. You don't have this database. All you can do without a connection to Oracle is run Stratum and statistics in files. Frontend won't display anything without a backend in Oracle.
